### PR TITLE
Support S3 directories

### LINKED ISSUE #25: Directory support
We serve multiple CloudFront distributions from a single S3 bucket via multiple S3 directories (prefixes) and CloudFront's origin path setting.

Currently, letsencrypt-s3front will upload its auth challenge file to the root of the S3 bucket (`[bucket]/.well-known/…`), which will fail verification ("Self-verify of challenge failed, authorization abandoned!").

I think this could be supported via a new flag that prepends the directory name to the `Key` keyword argument of `_perform_single` and `cleanup`.

letsencrypt-s3front v0.1.3.

### PR DESCRIPTION
**Pull request by tlvince**
Closes #25.

### CODE REVIEW

**Comment by Fuitad** [comment]
+1

I would greatly benefit from this.

**Comment by oronoa** [comment]
+1

**Comment by Redgwell** [comment]
Any idea when this PR will be merged?

**Comment by dlapiduz** [comment]
Sorry for the delay, this is now merged.

**Pull request merged**
